---
- name: "Create directory for backend"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Install dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Start backend application with PM2"
  shell: |
    cd ~/backend-app/
    pm2 stop default
    pm2 delete default
    pm2 start npm -- start